delete from GENRES;
ALTER TABLE GENRES ALTER COLUMN GENRE_ID RESTART WITH 1;

delete from USERS;
ALTER TABLE USERS ALTER COLUMN USER_ID RESTART WITH 1;

delete from FILMS;
ALTER TABLE FILMS ALTER COLUMN FILM_ID RESTART WITH 1;

delete from MPA;
ALTER TABLE MPA ALTER COLUMN MPA_ID RESTART WITH 1;

INSERT INTO GENRES (GENRE_NAME) VALUES ('Комедия');
INSERT INTO GENRES (GENRE_NAME) VALUES ('Драма');
INSERT INTO GENRES (GENRE_NAME) VALUES ('Мультфильм');
INSERT INTO GENRES (GENRE_NAME) VALUES ('Триллер');
INSERT INTO GENRES (GENRE_NAME) VALUES ('Документальный');
INSERT INTO GENRES (GENRE_NAME) VALUES ('Боевик');

INSERT INTO MPA (MPA_NAME) VALUES ('G');
INSERT INTO MPA (MPA_NAME) VALUES ('PG');
INSERT INTO MPA (MPA_NAME) VALUES ('PG-13');
INSERT INTO MPA (MPA_NAME) VALUES ('R');
INSERT INTO MPA (MPA_NAME) VALUES ('NC-17');